# dataset config
field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

# 字段类型设置
load_col:
  inter: [user_id, item_id, timestamp]



# 序列推荐设置
MAX_ITEM_LIST_LENGTH: 100          
ITEM_LIST_LENGTH_FIELD: item_length   

# model config

embedding_size: 128
hidden_size: 128
n_layers: 2
n_heads: 2
inner_size: 256
hidden_dropout_prob: 0.3
attn_dropout_prob: 0.3
learning_rate: 0.001 
weight_decay: 0.0001 
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'  

# 频域特定参数
global_ratio: 0.75
topk_factor: 0.75 
cutoff_ratio: 0.3
window_size: 5
decay_threshold: 0.3
novelty_boost: 1.0
contrast_weight: 0.5
freq_history_length: 10

# 负采样配置 (与BPR损失匹配)
train_neg_sample_args:
  distribution: uniform
  sample_num: 1

eval_setting: TO_LS,full 
metrics: ["Recall", "MRR","NDCG","Hit","Precision"] 
valid_metric: MRR@10
use_amp: True

# 训练设置
learner: adam
epochs: 20
train_batch_size: 4096  
eval_batch_size: 4096
stopping_step: 10
